--!strict

return {
	masked = {
		sourceSha256 = "e478c7e74f47357c150cc1c9c2c4690d1a1d50097e176f0d4d01230fb85368a9",
		body = [=[{"displayName":"fixture.semantic","description":"fixture.semantic"}]=],
	},
	unmasked = {
		sourceSha256 = "0741737c57554c4ee00c3b618e664e485aac73493f149fdca699b695b240a2d9",
		body = [=[{"path":"assets/999000111","revisionId":"1","revisionCreateTime":"2026-09-09T00:11:40.939034800Z","assetId":"999000111","displayName":"fixture.semantic","description":"fixture.semantic","assetType":"Model","creationContext":{"creator":{"groupId":"123456"}},"moderationResult":{"moderationState":"Approved"},"state":"Active"}]=],
	},
}
